/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class BinaryStdOut */

#ifndef _Included_BinaryStdOut
#define _Included_BinaryStdOut
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
