/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class BinaryStdIn */

#ifndef _Included_BinaryStdIn
#define _Included_BinaryStdIn
#ifdef __cplusplus
extern "C" {
#endif
#undef BinaryStdIn_EOF
#define BinaryStdIn_EOF -1L
#ifdef __cplusplus
}
#endif
#endif
